const CREATE_REVIEW_REQUEST = 'CREATE_REVIEW_REQUEST';
const DELETE_REVIEW_REQUEST = 'DELETE_REVIEW_REQUEST';
const CREATE_REVIEW_SUCCESS = 'CREATE_REVIEW_SUCCESS';
const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS';
const CREATE_REVIEW_FAILURE = 'CREATE_REVIEW_FAILURE';
const DELETE_REVIEW_FAILURE = 'DELETE_REVIEW_FAILURE';

const types = {
    CREATE_REVIEW_REQUEST,
    DELETE_REVIEW_REQUEST,
    CREATE_REVIEW_SUCCESS,
    DELETE_REVIEW_SUCCESS,
    CREATE_REVIEW_FAILURE,
    DELETE_REVIEW_FAILURE
}

export default types;