version: "3"

services:
  mybackend:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    depends_on:
      - mongo
    environment:
      - PORT=5000
      - API_HOST=localhost
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DATABASE=bookpage
      - NODE_ENV=development
      - CLIENT_URL=myfrontend
      - WAIT_HOSTS=mongo:27017
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    volumes:
      - /opt/app/node_modules
      - ./server:/opt/app

  mynginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./mynginx
    ports:
      - "9090:80"

  myfrontend:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /opt/app/node_modules
      - ./client:/opt/app
    environment:
      # Fixes bug where websocket connection
      - WDS_SOCKET_PORT=0
      - REACT_APP_SERVER_DOMAIN=http://localhost:9090/api

  mongo:
    image: mongo
    restart: always
