const GET_ALL_BOOKS_REQUEST = 'GET_ALL_BOOKS_REQUEST';
const CREATE_BOOK_REQUEST = 'CREATE_BOOK_REQUEST';
const DELETE_BOOK_REQUEST = 'DELETE_BOOK_REQUEST';
const UPDATE_BOOK_REQUEST = 'UPDATE_BOOK_REQUEST';
const GET_ONE_BOOK_REQUEST = "GET_ONE_BOOK_REQUEST";
const GET_BOOKS_BY_AUTHOR_REQUEST = "GET_BOOKS_BY_AUTHOR_REQUEST"

const GET_ALL_BOOKS_SUCCESS = 'GET_ALL_BOOKS_SUCCESS';
const CREATE_BOOK_SUCCESS = 'CREATE_BOOK_SUCCESS';
const DELETE_BOOK_SUCCESS = 'DELETE_BOOK_SUCCESS';
const UPDATE_BOOK_SUCCESS = 'UPDATE_BOOK_SUCCESS';
const GET_ONE_BOOK_SUCCESS = "GET_ONE_BOOK_SUCCESS";
const GET_BOOKS_BY_AUTHOR_SUCCESS = "GET_BOOKS_BY_AUTHOR_SUCCESS"

const GET_ALL_BOOKS_FAILURE = 'GET_ALL_BOOKS_FAILURE';
const CREATE_BOOK_FAILURE = 'CREATE_BOOK_FAILURE';
const DELETE_BOOK_FAILURE = 'DELETE_BOOK_FAILURE';
const UPDATE_BOOK_FAILURE = 'UPDATE_BOOK_FAILURE';
const GET_ONE_BOOK_FAILURE = "GET_ONE_BOOK_FAILURE";
const GET_BOOKS_BY_AUTHOR_FAILURE = "GET_BOOKS_BY_AUTHOR_FAILURE"

const loadingTypes = {
    GET_ALL_BOOKS_REQUEST,
    CREATE_BOOK_REQUEST,
    DELETE_BOOK_REQUEST,
    UPDATE_BOOK_REQUEST,
    GET_ONE_BOOK_REQUEST,
    GET_BOOKS_BY_AUTHOR_REQUEST,
    GET_ALL_BOOKS_SUCCESS,
    CREATE_BOOK_SUCCESS,
    DELETE_BOOK_SUCCESS,
    UPDATE_BOOK_SUCCESS,
    GET_ONE_BOOK_SUCCESS,
    GET_BOOKS_BY_AUTHOR_SUCCESS,
    GET_ALL_BOOKS_FAILURE,
    CREATE_BOOK_FAILURE,
    DELETE_BOOK_FAILURE,
    UPDATE_BOOK_FAILURE,
    GET_ONE_BOOK_FAILURE,
    GET_BOOKS_BY_AUTHOR_FAILURE
}

export default loadingTypes;