const SET_BOOK_REQUEST_STATUS = "SET_BOOK_REQUEST_STATUS"
const SET_AUTHOR_REQUEST_STATUS = "SET_AUTHOR_REQUEST_STATUS"

const types = {
    SET_BOOK_REQUEST_STATUS,
    SET_AUTHOR_REQUEST_STATUS
}

export default types;