const categories = [
    'Action and Adventure',
    'Classics',
    'Comic Book or Graphic Novel',
    'Detective and Mystery',
    'Fantasy',
    'Historical Fiction',
    'Horror',
    'Literary Fiction',
    'Romance',
    'Science Fiction',
    'Short Stories',
    'Suspense and Thrillers',
    'Women\'s Fiction',
    'Biographies and Autobiographies',
    'Cookbooks',
    'Essays',
    'History',
    'Memoir',
    'Poetry',
    'Self-Help',
    'True Crime',
]

export default categories
