const GET_ALL_AUTHORS = 'GET_ALL_AUTHORS';
const CREATE_AUTHOR = 'CREATE_AUTHOR';
const DELETE_AUTHOR = 'DELETE_AUTHOR';
const UPDATE_AUTHOR = 'UPDATE_AUTHOR';
const GET_AUTHORS = "GET_AUTHORS";

const types = {
    GET_ALL_AUTHORS,
    CREATE_AUTHOR,
    DELETE_AUTHOR,
    UPDATE_AUTHOR,
    GET_AUTHORS
}

export default types;